# .github/workflows/build.yml
name: Build & Push OpenResty Static

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: openresty-static

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get latest OpenResty version
      id: version
      run: |
        LATEST=$(curl -s https://openresty.org/en/ | grep -Po '(?<=OpenResty )\d+\.\d+\.\d+\.\d+(?= Released)' | head -1)
        echo "LATEST=$LATEST" >> $GITHUB_OUTPUT

    - name: Prepare tags
      id: tags
      run: |
        TS=$(date -u +"%Y-%m-%d-%H%M%S")
        V=${{ steps.version.outputs.LATEST }}
        echo "TAG_VER=v${V}-${TS}" >> $GITHUB_OUTPUT
        echo "TAG_LATEST=latest" >> $GITHUB_OUTPUT

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.tags.outputs.TAG_VER }}
          ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.tags.outputs.TAG_LATEST }}

        provenance: false
